import smtplib
from email.mime.text import MIMEText

# Configuration
port = 465
smtp_server = "webhosting2052.is.cc"
login = "api"  # Your login generated by Mailtrap
password = "Bisleri12!@"  # Your password generated by Mailtrap

sender_email = "administrator@sahasra.ai"
receiver_email = "no-reply@sahasra.ai"

# Plain text content
text = """\
TEST TEST 
"""

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "Plain text email"
message["From"] = sender_email
message["To"] = receiver_email

# Send the email
with smtplib.SMTP_SSL(smtp_server, port) as server:
  # Secure the connection
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')